[hosts.node1]
role = "head"
hostname = "node-3542"
ssh_alias = "vonk-node-1"
lan_ip = "192.168.1.211"
memory_bytes = 130663231488
root_disk_bytes = 4031871553536
root_free_bytes = 3787009835008
driver = "580.173.02"
docker = "29.2.1"
compose = "5.0.2"
earlyoom_active = false
earlyoom_enabled = false

[hosts.node1.fabric]
mtu = 1500
link_rate_mbps = 200000
default_route = false
NCCL_SOCKET_IFNAME = "=enp1s0f1np1,enP2p1s0f1np1"
NCCL_IB_HCA = "=rocep1s0f1:1,roceP2p1s0f1:1"
NCCL_IB_GID_INDEX = 3
TP_SOCKET_IFNAME = "enp1s0f1np1,enP2p1s0f1np1"
GLOO_SOCKET_IFNAME = "enp1s0f1np1,enP2p1s0f1np1"

[hosts.node1.fabric.function100]
fabric_ip = "192.168.100.10"
peer_ip = "192.168.100.11"
interface = "enp1s0f1np1"
hca = "rocep1s0f1"
gid_index = 3

[hosts.node1.fabric.function101]
fabric_ip = "192.168.101.10"
peer_ip = "192.168.101.11"
interface = "enP2p1s0f1np1"
hca = "roceP2p1s0f1"
gid_index = 3

[hosts.node2]
role = "worker"
hostname = "node-2297"
ssh_alias = "vonk-node-2"
lan_ip = "192.168.1.212"
memory_bytes = 130663231488
root_disk_bytes = 4031871553536
root_free_bytes = 3786993606656
driver = "580.173.02"
docker = "29.2.1"
compose = "5.0.2"
earlyoom_active = false
earlyoom_enabled = false

[hosts.node2.fabric]
mtu = 1500
link_rate_mbps = 200000
default_route = false
NCCL_SOCKET_IFNAME = "=enp1s0f1np1,enP2p1s0f1np1"
NCCL_IB_HCA = "=rocep1s0f1:1,roceP2p1s0f1:1"
NCCL_IB_GID_INDEX = 3
TP_SOCKET_IFNAME = "enp1s0f1np1,enP2p1s0f1np1"
GLOO_SOCKET_IFNAME = "enp1s0f1np1,enP2p1s0f1np1"

[hosts.node2.fabric.function100]
fabric_ip = "192.168.100.11"
peer_ip = "192.168.100.10"
interface = "enp1s0f1np1"
hca = "rocep1s0f1"
gid_index = 3

[hosts.node2.fabric.function101]
fabric_ip = "192.168.101.11"
peer_ip = "192.168.101.10"
interface = "enP2p1s0f1np1"
hca = "roceP2p1s0f1"
gid_index = 3

[fabric]
topology = "direct"
default_route = false
