#!/bin/sh
set -eu

if [ "${1:-}" = remove ]; then
    deb-systemd-invoke stop vonk-agent-supervisor.service >/dev/null || true
    deb-systemd-invoke stop vonk-agent.service >/dev/null || true
    deb-systemd-invoke stop vonk-agent-helper.socket >/dev/null || true
    deb-systemd-helper disable vonk-agent-supervisor.service >/dev/null || true
    deb-systemd-helper disable vonk-agent-helper.socket >/dev/null || true
fi

exit 0
