/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent List */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enrollments */
        get: operations["listAgentEnrollments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/enrollments/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Grant */
        post: operations["createEnrollmentGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/enrollments/{enrollment_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approveAgentEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/enrollments/{enrollment_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["rejectAgentEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/nodes/{node_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revokeAgentNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit View */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Change */
        post: operations["submitChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document View */
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/endpoints/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endpoint View */
        get: operations["getPublishedEndpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fleet View */
        get: operations["getFleetStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs View */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job View */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Log List */
        get: operations["listJobLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/logs/{digest}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Log Content */
        get: operations["getJobLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Job */
        post: operations["resumeJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node Status View */
        get: operations["getNodeStatuses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{profile_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profile Reconcile Plan */
        post: operations["planProfileReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Proposal Preview */
        post: operations["previewProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile */
        post: operations["applyReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile Plan */
        post: operations["planReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reconciliations/{reconciliation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Reconciliation */
        post: operations["cancelReconciliation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repository": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repository View */
        get: operations["getRepository"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentSummary */
        AgentSummary: {
            /** Capabilities */
            capabilities: string[];
            /** Certificate Expires At */
            certificate_expires_at: string | null;
            /** Last Seen Age Seconds */
            last_seen_age_seconds?: number | null;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Node Id */
            node_id: string;
            /** Protocol Version */
            protocol_version?: number | null;
            /** Stale */
            stale: boolean;
            /** State */
            state: string;
        };
        /** AgentsResponse */
        AgentsResponse: {
            /** Agents */
            agents: components["schemas"]["AgentSummary"][];
        };
        /** BoundedErrorResponse */
        BoundedErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** ChangeRequest */
        ChangeRequest: {
            /** Proposal Digest */
            proposal_digest: string;
        };
        /** EndpointResponse */
        EndpointResponse: {
            /** Alias */
            alias: string;
            /** Api Base */
            api_base: string;
            /** Expires At */
            expires_at: string;
            /** Generation */
            generation: number;
            /** Node Id */
            node_id: string;
            /** Observed At */
            observed_at: string;
            /** Plan Digest */
            plan_digest: string;
            /** State */
            state: string;
        };
        /** EnrollmentDecisionResponse */
        EnrollmentDecisionResponse: {
            /** Id */
            id: string;
            /** Node Id */
            node_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "approved" | "rejected";
        };
        /** EnrollmentGrantResponse */
        EnrollmentGrantResponse: {
            /** Expires At */
            expires_at: string;
            /** Id */
            id: string;
            /** Node Id */
            node_id: string;
            /** Token */
            token: string;
        };
        /** EnrollmentListResponse */
        EnrollmentListResponse: {
            /** Enrollments */
            enrollments: components["schemas"]["EnrollmentSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** EnrollmentSummary */
        EnrollmentSummary: {
            /** Agent Digest */
            agent_digest: string;
            /** Boot Id */
            boot_id: string;
            /** Certificate Fingerprint */
            certificate_fingerprint?: string | null;
            /** Certificate Serial */
            certificate_serial?: string | null;
            /** Created At */
            created_at: string;
            /** Csr Public Key Fingerprint */
            csr_public_key_fingerprint: string;
            /** Decided At */
            decided_at?: string | null;
            /** Decision Actor */
            decision_actor?: string | null;
            /** Hardware Fingerprint */
            hardware_fingerprint: string;
            /** Host Key Fingerprint */
            host_key_fingerprint: string;
            /** Id */
            id: string;
            /** Node Id */
            node_id: string;
            /** Rejection Reason */
            rejection_reason?: string | null;
            /** State */
            state: string;
        };
        /** FleetStatusResponse */
        FleetStatusResponse: {
            /** Commit */
            commit: string;
            /** Nodes */
            nodes: components["schemas"]["NodeStatus"][];
        };
        /** GrantRequest */
        GrantRequest: {
            /** Node Id */
            node_id: string;
            /** Ttl Seconds */
            ttl_seconds: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetailResponse */
        JobDetailResponse: {
            /** Base Commit */
            base_commit: string;
            /** Current Attempt */
            current_attempt: number;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Operations */
            operations: components["schemas"]["JobOperationResponse"][];
            progress: components["schemas"]["JobProgress"];
            /** Reconciliation Id */
            reconciliation_id: string | null;
            /** State */
            state: string;
            /** Status Reason */
            status_reason: string | null;
            /** Targets */
            targets: string[];
        };
        /** JobLogsResponse */
        JobLogsResponse: {
            /** Digests */
            digests: string[];
            /** Job Id */
            job_id: string;
        };
        /** JobOperationProgress */
        JobOperationProgress: {
            /** Phase */
            phase: string;
        };
        /** JobOperationResponse */
        JobOperationResponse: {
            /** Attempt */
            attempt: number;
            /** Graph Operation Id */
            graph_operation_id?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Node Id */
            node_id: string;
            progress?: components["schemas"]["JobOperationProgress"] | null;
            /** State */
            state: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** JobProgress */
        JobProgress: {
            /** Completed */
            completed: number;
            /** Failed */
            failed: number;
            /** Running */
            running: number;
            /** Total */
            total: number;
        };
        /** JobResumeResponse */
        JobResumeResponse: {
            /** Id */
            id: string;
            /** State */
            state: string;
        };
        /** JobSummary */
        JobSummary: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** State */
            state: string;
        };
        /** JobsResponse */
        JobsResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
        };
        /** NodeStatus */
        NodeStatus: {
            /** Agent Last Seen At */
            agent_last_seen_at?: string | null;
            /**
             * Agent Online
             * @default false
             */
            agent_online: boolean;
            /**
             * Agent State
             * @default unregistered
             */
            agent_state: string;
            /** Certificate Expires At */
            certificate_expires_at?: string | null;
            /** Certificate Expiry Seconds */
            certificate_expiry_seconds?: number | null;
            /**
             * Compatibility
             * @default unknown
             */
            compatibility: string;
            /** Disk Available Bytes */
            disk_available_bytes: number;
            /** Display Name */
            display_name: string;
            /** Healthy */
            healthy: boolean | null;
            /** Hostname */
            hostname: string;
            /** Id */
            id: string;
            /** Labels */
            labels: {
                [key: string]: string;
            };
            /** Last Seen Age Seconds */
            last_seen_age_seconds?: number | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Lifecycle */
            lifecycle: string;
            /** Memory Available Bytes */
            memory_available_bytes: number;
            /** Probe Age Seconds */
            probe_age_seconds?: number | null;
            /** Profile */
            profile: string | null;
            /** Stale */
            stale: boolean;
        };
        /** PlanEndpoint */
        PlanEndpoint: {
            /** Path */
            path: string;
            /** Port */
            port: number;
            /**
             * Scheme
             * @enum {string}
             */
            scheme: "http" | "https";
        };
        /** PlanInputDigests */
        PlanInputDigests: {
            [key: string]: string;
        };
        /** PlanOperation */
        PlanOperation: {
            /** Compensation Kind */
            compensation_kind?: string | null;
            /** Dependencies */
            dependencies: string[];
            /** Kind */
            kind: string;
            /** Node Id */
            node_id: string;
            /** Operation Id */
            operation_id: string;
            /** Payload Digest */
            payload_digest: string;
            /** Workload Id */
            workload_id: string;
        };
        /** PlanOperationGraph */
        PlanOperationGraph: {
            /** Base Commit */
            base_commit: string;
            /** Nodes */
            nodes: components["schemas"]["PlanOperation"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Targets */
            targets: string[];
        };
        /** PlanPlacements */
        PlanPlacements: {
            [key: string]: string[];
        };
        /** PlanPrepareRequest */
        PlanPrepareRequest: {
            /** Adapter Id */
            adapter_id: string;
            /** Profile Digest */
            profile_digest: string;
            /** Release Digest */
            release_digest: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Workload Id */
            workload_id: string;
        };
        /** PlanQuota */
        PlanQuota: {
            /** Requests Per Minute */
            requests_per_minute: number;
            /** Tokens Per Minute */
            tokens_per_minute: number;
        };
        /** PlanRelease */
        PlanRelease: {
            /** Definition Hash */
            definition_hash: string;
            endpoint: components["schemas"]["PlanEndpoint"];
            /** Manifest Path */
            manifest_path: string;
            /** Manifest Sha256 */
            manifest_sha256: string;
            release_request: components["schemas"]["PlanReleaseRequest"];
            workload_requests: components["schemas"]["PlanWorkloadRequests"];
        };
        /** PlanReleaseRequest */
        PlanReleaseRequest: {
            /** Adapter Id */
            adapter_id: string;
            /** Oci Manifest Digest */
            oci_manifest_digest: string;
            /** Provenance Digest */
            provenance_digest: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Target Digest */
            target_digest: string;
            /** Target Name */
            target_name: string;
        };
        /** PlanReleases */
        PlanReleases: {
            [key: string]: components["schemas"]["PlanRelease"];
        };
        /** PlanRoute */
        PlanRoute: {
            /** Entrypoint Node Id */
            entrypoint_node_id: string;
            /** Nodes */
            nodes: string[];
            /** Path */
            path: string;
            /** Port */
            port: number;
            quota: components["schemas"]["PlanQuota"];
            /** Quota Digest */
            quota_digest: string;
            /**
             * Scheme
             * @enum {string}
             */
            scheme: "http" | "https";
            /** Workload Id */
            workload_id: string;
        };
        /** PlanRoutes */
        PlanRoutes: {
            [key: string]: components["schemas"]["PlanRoute"];
        };
        /** PlanStartRequest */
        PlanStartRequest: {
            /** Adapter Id */
            adapter_id: string;
            /** Preparation Digest */
            preparation_digest: string;
            /** Release Digest */
            release_digest: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Workload Id */
            workload_id: string;
        };
        /** PlanVerifyRequest */
        PlanVerifyRequest: {
            /** Adapter Id */
            adapter_id: string;
            /** Expected Digest */
            expected_digest: string;
            /** Release Digest */
            release_digest: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Workload Id */
            workload_id: string;
        };
        /** PlanWorkloadRequest */
        PlanWorkloadRequest: {
            /** Adapter Id */
            adapter_id: string;
            /** Release Digest */
            release_digest: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: 1;
            /** Workload Id */
            workload_id: string;
        };
        /** PlanWorkloadRequests */
        PlanWorkloadRequests: {
            health: components["schemas"]["PlanWorkloadRequest"];
            prepare: components["schemas"]["PlanPrepareRequest"];
            start: components["schemas"]["PlanStartRequest"];
            stop: components["schemas"]["PlanWorkloadRequest"];
            verify: components["schemas"]["PlanVerifyRequest"];
        };
        /** ProposalChangeRequest */
        ProposalChangeRequest: {
            /** Document */
            document: {
                [key: string]: unknown;
            };
            /** Path */
            path: string;
        };
        /** ProposalRequest */
        ProposalRequest: {
            /** Base Commit */
            base_commit: string;
            /** Changes */
            changes: components["schemas"]["ProposalChangeRequest"][];
        };
        /** ReconciliationAcceptedResponse */
        ReconciliationAcceptedResponse: {
            /** Base Commit */
            base_commit: string;
            /** Job Id */
            job_id: string;
            /** Reconciliation Id */
            reconciliation_id?: string | null;
            /** State */
            state: string;
        };
        /** ReconciliationCancelRequest */
        ReconciliationCancelRequest: {
            /** Reason */
            reason: string;
        };
        /** ReconciliationPlanRequest */
        ReconciliationPlanRequest: {
            /** Commit */
            commit: string;
            /** Profile Id */
            profile_id: string;
        };
        /** ReconciliationPlanResponse */
        ReconciliationPlanResponse: {
            /** Agent Protocol Range */
            agent_protocol_range: number[];
            /** Commit */
            commit: string;
            /** Digest */
            digest: string;
            input_digests: components["schemas"]["PlanInputDigests"];
            operation_graph: components["schemas"]["PlanOperationGraph"];
            placements: components["schemas"]["PlanPlacements"];
            /** Reconciliation Id */
            reconciliation_id: string;
            releases: components["schemas"]["PlanReleases"];
            routes: components["schemas"]["PlanRoutes"];
            /** Targets */
            targets: string[];
        };
        /** ReconciliationRequest */
        ReconciliationRequest: {
            /** Plan Digest */
            plan_digest: string;
        };
        /** RejectRequest */
        RejectRequest: {
            /** Reason */
            reason: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    listAgentEnrollments: {
        parameters: {
            query?: {
                cursor?: string | null;
                state?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    createEnrollmentGrant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentGrantResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    approveAgentEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentDecisionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    rejectAgentEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentDecisionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    revokeAgentNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    listAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    submitChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                commit?: string | null;
                path?: string | null;
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPublishedEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alias: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    getFleetStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetStatusResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listJobLogs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobLogsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    getJobLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    resumeJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResumeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    getNodeStatuses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FleetStatusResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    planProfileReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationPlanResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    previewProposal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    applyReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconciliationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationAcceptedResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    planReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconciliationPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationPlanResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    cancelReconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reconciliation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconciliationCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoundedErrorResponse"];
                };
            };
        };
    };
    getRepository: {
        parameters: {
            query?: {
                commit?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
