import {useEffect, useState} from "react";
import type {ControlApi, ProposalPreview} from "../api/types";
import {ProposalDiff} from "./proposal-diff";
export function RepositoryEditor({api, kind}: {api: ControlApi; kind: "models" | "profiles"}) {
  const [base, setBase] = useState(""); const [documents, setDocuments] = useState<string[]>([]); const [id, setId] = useState(""); const [name, setName] = useState("");
  const [repository, setRepository] = useState(""); const [revision, setRevision] = useState(""); const [preview, setPreview] = useState<ProposalPreview>(); const [confirmed, setConfirmed] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { api.documents(kind).then(result => {setBase(result.commit); setDocuments(result.documents);}).catch(error => setMessage(String(error))); }, [api, kind]);
  const path = kind === "profiles" ? `config/cluster-profiles/${id}.toml` : `config/workloads/${id}.toml`;
  async function previewChange(event: React.FormEvent) { event.preventDefault(); setConfirmed(false); setMessage(""); if (!base || !/^[a-z0-9][a-z0-9-]{1,63}$/.test(id) || !name.trim()) {setMessage("Provide a valid ID, name, and loaded base commit."); return;} const document: Record<string, unknown> = {schema_version: 2, id, name}; if (kind === "models") {if (!repository || !revision) {setMessage("Model repository and immutable revision are required."); return;} document.repository = repository; document.revision = revision;} setPreview(await api.preview({base_commit: base, changes: [{path, document}]})); }
  async function submit() { if (preview && confirmed) {const result = await api.submit(preview.digest); setMessage(`Submitted: ${String(result.mode ?? result.pull_request ?? "accepted")}`);} }
  return <div><section><h2>{kind === "profiles" ? "Profiles" : "Models"}</h2><p>Repository-backed definitions at <code>{base || "loading…"}</code></p><ul>{documents.map(document => <li key={document}><code>{document}</code></li>)}</ul></section><form onSubmit={previewChange} aria-label={`Create ${kind === "profiles" ? "profile" : "model"} proposal`}><h3>Create {kind === "profiles" ? "profile" : "model"}</h3><label>ID<input value={id} onChange={e => setId(e.target.value)} required /></label><label>Name<input value={name} onChange={e => setName(e.target.value)} required /></label>{kind === "models" && <><label>Repository<input value={repository} onChange={e => setRepository(e.target.value)} required /></label><label>Immutable revision<input value={revision} onChange={e => setRevision(e.target.value)} required /></label></>}<button type="submit">Preview change</button></form>{message && <p role="status">{message}</p>}{preview && <><ProposalDiff preview={preview}/><label><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)}/>I reviewed the affected documents and canonical diff</label><button type="button" disabled={!confirmed} onClick={submit}>Submit change</button></>}</div>;
}
