schema_version = 1
deployment_id = "mia-deepseek-dual"
family_id = "mia-deepseek"
release_digest = "372ac4707f006a7bbba7c49db7577687151cd00ac3f1ad93a5b67addb72bcd5a"
arguments = []

[selector]
node_count = 2
required_labels = {}
preferred_node_ids = []

[secrets]

[ports]
inference = 8888

[routing]
alias = "deepseek-agent-dual"
port = "inference"

[resources]
memory_bytes = 120000000000
storage_bytes = 375809638400
gpu_count = 2
